#!/bin/bash
#
# Build & merge rpm docs for each stable version series

PROJECT=rpm
REPO_URL=https://github.com/rpm-software-management/rpm
REPO_DIR=_build/$PROJECT
BARE_DIR=$REPO_DIR/bare
DEST_DIR=docs

get_data() {
    yq -ot ".[] | select(.name == \"$PROJECT\")$1" _data/projects.yml | xargs
}

add_worktree() {
    [ -d $REPO_DIR/$1 ] && git -C $BARE_DIR worktree remove ../$1
    git -C $BARE_DIR worktree add ../$1
}

build() {
    local tree=$REPO_DIR/$1
    local dest=$DEST_DIR/$2

    local base=".docs.[] | select(.series == \"$2\")"
    local make=$(get_data "${base}.make")
    local root=$(get_data "${base}.root")
    local paths=$(get_data "${base}.paths")

    add_worktree $1
    mkdir -p $dest

    if [ $make == true ]; then
        cmake -B ${tree}/_build -S $tree
        make -C ${tree}/_build pages
    fi

    for path in $paths; do
        cp -r ${tree}/${root}/${path} ${dest}/
    done
}

[ -d $BARE_DIR ] || git clone --bare $REPO_URL $BARE_DIR
for series in $(get_data .docs.[].series); do
    build $PROJECT-$series $series
done
