#!/bin/bash
#
# Build & merge rpm docs on the given branch into this site

SCRIPT_DIR=$(dirname $(readlink -f $0))

REF_NAME=$1
REPO_URL=https://github.com/rpm-software-management/rpm
REPO_DIR=_build/rpm/$REFNAME
DOCS_DIR=$SCRIPT_DIR/doc/$REF_NAME

cd $SCRIPT_DIR
mkdir -p $REPO_DIR $DOCS_DIR
cd $REPO_DIR

if [ -d src ]; then
    git -C src pull
else
    git clone --branch $REF_NAME $REPO_URL src
fi

cp src/docs/manual/*.md $DOCS_DIR/
