#!/bin/bash
#
# Build & merge rpm docs for each stable version series

PROJECT=rpm
REPO_URL=https://github.com/rpm-software-management/rpm
REPO_DIR=_build/$PROJECT
BARE_DIR=$REPO_DIR/bare
DOCS_DIR=doc

get_data() {
    yq -ot ".[] | select(.name == \"$PROJECT\")$1" _data/projects.yml | xargs
}

add_worktree() {
    [ -d $REPO_DIR/$1 ] && git -C $BARE_DIR worktree remove ../$1
    git -C $BARE_DIR worktree add ../$1
}

merge_pages() {
    local tree=$2
    local dest=$DOCS_DIR/$3
    local pages=$(get_data ".docs[] | select(.type == \"$1\").path")
    mkdir -p $dest
    for page in $pages; do
        cp $REPO_DIR/${tree}/${page} ${dest}/
    done
}

build() {
    add_worktree $1
    merge_pages guide $1 $2
}

[ -d $BARE_DIR ] || git clone --bare $REPO_URL $BARE_DIR
build master master
for series in $(get_data .stable); do
    build $PROJECT-$series $series
done
